spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bmi_calculate
    username: root
    password: nuwin47212
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
